version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: project_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-uroot', '-p${DB_ROOT_PASS}']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-networks

  app:
    build: .
    container_name: project_app
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000']
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - '3001:3000'
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    networks:
      - app-networks
    command: npm start

volumes:
  db_data:

networks:
  app-networks:
    driver: bridge
